// core/assetManifest.ts

export const assetManifest = {
  backgrounds: {
    areaTerbuka: [
      'bg_area_terbuka_01.jpeg',
      'bg_area_terbuka_02.jpeg',
      'bg_area_terbuka_03.jpeg',
      'bg_area_terbuka_04.jpeg',
    ],
    gangSampah: [
      'bg_gang_sampah_01.jpeg',
      'bg_gang_sampah_02.jpeg',
      'bg_gang_sampah_03.jpeg',
      'bg_gang_sampah_04.jpeg',
    ],
    hqRepublik: [
      'bg_hq_republik_01.jpeg',
      'bg_hq_republik_02.jpeg',
      'bg_hq_republik_03.jpeg',
      'bg_hq_republik_04.jpeg',
    ],
    jalanRayaJembatan: [
      'bg_jalanraya_jembatan_01.jpeg',
      'bg_jalanraya_jembatan_02.jpeg',
      'bg_jalanraya_jembatan_03.jpeg',
      'bg_jalanraya_jembatan_04.jpeg',
    ],
    ruanganKamarTidur: [
      'bg_ruangan_kamar_tidur_01.jpeg',
      'bg_ruangan_kamar_tidur_02.jpeg',
      'bg_ruangan_kamar_tidur_03.jpeg',
      'bg_ruangan_kamar_tidur_04.jpeg',
    ],
    kantorKelasRuang: [
      'bg_kantor_kelas_ruang_01.jpeg',
      'bg_kantor_kelas_ruang_02.jpeg',
      'bg_kantor_kelas_ruang_03.jpeg',
      'bg_kantor_kelas_ruang_04.jpeg',
    ],
    labPustakaRiset: [
      'bg_lab_pustaka_riset_01.jpeg',
      'bg_lab_pustaka_riset_02.jpeg',
      'bg_lab_pustaka_riset_03.jpeg',
    ],
    malLobiAula: [
      'bg_mal_lobi_balkon_aula_01.jpeg',
      'bg_mal_lobi_balkon_aula_02.jpeg',
      'bg_mal_lobi_balkon_aula_03.jpeg',
      'bg_mal_lobi_balkon_aula_04.jpeg',
    ],
    monumenPuing: [
      'bg_monumen_puing_reruntuhan_01.jpeg',
      'bg_monumen_puing_reruntuhan_02.jpeg',
    ],
    pasarSaudagar: [
      'bg_pasar_saudagar_01.jpeg',
      'bg_pasar_saudagar_02.jpeg',
      'bg_pasar_saudagar_03.jpeg',
      'bg_pasar_saudagar_04.jpeg',
    ],
    relMrtKereta: [
      'bg_rel_mrt_kereta_lorong_01.jpeg',
      'bg_rel_mrt_kereta_lorong_02.jpeg',
      'bg_rel_mrt_kereta_lorong_03.jpeg',
      'bg_rel_mrt_kereta_lorong_04.jpeg',
    ],
    stadionGudang: [
      'bg_stadion_gudang_logistik_01.jpeg',
      'bg_stadion_gudang_logistik_02.jpeg',
      'bg_stadion_gudang_logistik_03.jpeg',
      'bg_stadion_gudang_logistik_04.jpeg',
    ],
    stasiunMrt: [
      'bg_stasiun_mrt_01.jpeg',
      'bg_stasiun_mrt_02.jpeg',
      'bg_stasiun_mrt_03.jpeg',
      'bg_stasiun_mrt_04.jpeg',
    ],
    tamanKota: [
      'bg_taman_kota_01.jpeg',
      'bg_taman_kota_02.jpeg',
      'bg_taman_kota_03.jpeg',
      'bg_taman_kota_04.jpeg',
    ],
    tendaMarkasSurvivor: [
      'bg_tenda_alun_alun_markas_survivor_01.jpeg',
      'bg_tenda_alun_alun_markas_survivor_02.jpeg',
      'bg_tenda_alun_alun_markas_survivor_03.jpeg',
      'bg_tenda_alun_alun_markas_survivor_04.jpeg',
    ],
    warungMakan: [
      'bg_warung_makan_01.jpeg',
      'bg_warung_makan_02.jpeg',
      'bg_warung_makan_03.jpeg',
      'bg_warung_makan_04.jpeg',
    ],
  },
  npcPortraits: {
    generic: [
      'npc_warga_01.png',
      'npc_warga_02.png',
      'npc_warga_03.png',
      'npc_warga_04.png',
      'npc_warga_06.png',
      'npc_warga_07.png',
      'penyintas_biasa.png',
    ],
    playerArchetypes: [
        'player_pemulung.png',
        'player_mantan_tentara.png',
        'player_teknisi_jalanan.png',
        'player_negosiator_pasar_gelap.png',
        'player_kurir_cepat.png',
        'player_pustakawan_kiamat.png',
        'player_seniman_grafiti.png',
        'player_pengawal_pribadi.png',
        'player_petani_hidroponik.png',
        'player_kultis_puing.png'
    ],
    companions: [
        'companion_ayra.png',
        'companion_davina.png',
        'companion_raizen.png',
    ],
  },
  factionPortraits: {
    geng_bangsat: [
        'faksi_geng_bangsat_leader.png',
        'faksi_geng_bangsat_01.png',
        'faksi_geng_bangsat_02.png',
        'faksi_geng_bangsat_03.png',
        'faksi_geng_bangsat_04.png',
    ],
    pemburu_agraria: [
        'faksi_pemburu_agraria_leader.png',
        'faksi_pemburu_agraria_01.png',
        'faksi_pemburu_agraria_02.png',
        'faksi_pemburu_agraria_03.png',
        'faksi_pemburu_agraria_04.png',
        'faksi_pemburu_agraria_05.png',
    ],
    republik_merdeka: [
        'faksi_republik_merdeka_leader.png',
        'faksi_republik_merdeka_01.png',
        'faksi_republik_merdeka_02.png',
        'faksi_republik_merdeka_03.png',
        'faksi_republik_merdeka_04.png',
    ],
    saudagar_jalanan: [
        'faksi_saudagar_jalanan_01.png',
        'faksi_saudagar_jalanan_02.png',
        'faksi_saudagar_jalanan_03.png',
        'faksi_saudagar_jalanan_04.png',
        'penyintas_pedagang_item.png',
        'penyintas_pedagang_senjata.png',
        'warga_pedagang_reliks.png',
    ],
    sekte_pustaka: [
        'faksi_sekte_pustaka_leader.png',
        'faksi_sekte_pustaka_01.png',
        'faksi_sekte_pustaka_02.png',
        'faksi_sekte_pustaka_03.png',
        'faksi_sekte_pustaka_04.png',
        'faksi_sekte_pustaka_05.png',
    ],
    sisa_kemanusiaan: [
        'pemimpin_sisa_kemanusiaan.png',
        'warga_sisa_kemanusiaan.png',
    ],
    gerombolan_besi: [
        'pemimpin_gerombolan_besi.png',
        'warga_gerombolan_besi.png',
    ],
    teknokrat: [
        'pemimpin_teknokrats.png',
        'warga_teknokrats.png',
    ],
  },
  enemyPortraits: {
      anomali: [
          'musuh_anomali_brainrot_01.png',
          'musuh_anomali_brainrot_02.png',
          'musuh_anomali_brainrot_03.png',
          'musuh_anomali_fungus_01.png',
          'musuh_anomali_fungus_02.png',
          'musuh_anomali_fungus_03.png',
          'musuh_anomali_kumbang_01.png',
          'musuh_anomali_queen.png',
          'musuh_anomali_skull_01.png',
          'musuh_anomali_skull_02.png',
          'musuh_anomali_skull_03.png',
          'musuh_anomali_skull_04.png',
      ],
      raider: [
          'musuh_raider_01.png',
          'musuh_raider_02.png',
          'musuh_raider_03.png',
      ],
      drones: [
        'musuh_drone_nyamuk.png',
        'musuh_drone_kecil_semut.png',
        'musuh_drone_besar_kumbang.png',
        'musuh_drone_besar_labalaba.png',
        'musuh_drone_laser_lalat.png',
        'musuh_drone_laser_serangga.png',
        'musuh_drone_kecil_labalaba.png',
      ],
      mutantDogs: [
        'musuh_anjing_mutan_reptil.png',
        'musuh_anjing_mutan_bertanduk.png',
        'musuh_anjing_mutan_iblis.png',
        'musuh_anjing_mutan_beracun.png',
        'musuh_anjing_mutan_berduri.png',
        'musuh_anjing_mutan_selokan.png',
        'musuh_anjing_mutan_jalanan.png',
      ],
  }
};